### ISSUE TITLE
Orden interno repositorio

### ISSUE THREAD

**Issue by ajcanepa** [LuciaVitores/Automatizacion_PDF_scraping#23]
Hola @LuciaVitores
Mirando tu repositorio te recomendaría ordenarlo un poco, considerando:

- Crear algún release antes de la entrega. No es necesario que _haya solo un release_, pero dado las fechas con que haya uno bastaría.
- Ordenar la documentación dentro de algún directorio. No queda muy ordenado que los documentos de la memoria estén al mismo nivel que el código de tu cuaderno de python.
- Ya que es un TFG de la universidad de Burgos, agregar el logo (ver [aquí](https://www.ubu.es/servicio-de-publicaciones-e-imagen-institucional/imagen-institucional/imagen-corporativa-de-la-universidad-de-burgos/diseno-de-la-marca-principal)) de la universidad en el README.

**Comment by ajcanepa** [comment]
Además,
Mirando el fichero `FuncionesGit.txt`, pareceria que son unos apuntes para tí, para que no se te olviden los comandos. Creo que de cara a incorporarles en tu TFG, estarían mejor en los anexos correspondientes. Si incorporas el uso de github a nivel usuario/programador, yo les colocaría allí.

**Comment by LuciaVitores** [comment]
Habiendo eliminado el fichero FuncionesGit.txt para introducirlo mejor en la memoria, ordenado la ordenación del repositorio y modificado el fichero README, se cierra este Issue, quedando pendiente el release.
