### ISSUE TITLE
Revisón final orden repositorio y último Release

### ISSUE THREAD

**Issue by ajcanepa** [LuciaVitores/Automatizacion_PDF_scraping#32]
Hola @LuciaVitores ,
He visto resultados en el `INPUT` y alguna otra cosa un poco "desordenada" por ahí.

Además, estaría bien que antes de presentar tengas el release final del proyecto, para que presentes esta otra semana con el repositorio ordenado y "acabado".

Saludos,

**Comment by LuciaVitores** [comment]
Hola @ajcanepa, 
Ya he reorganizado el repositorio. Lo reviso de nuevo antes de cerrar este Issue y en cuanto lo tenga, comienzo con el release. 
Un saludo y gracias.

**Comment by ajcanepa** [comment]
[like]  ANTONIO JESUS CANEPA ONETO reacted to your message:
________________________________
